services:
  database:
    image: postgres:14-alpine
    container_name: mariodb
    ports:
      - "5432:5432"
    env_file: .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5